[tox]
requires =
    tox>=4.2
env_list =
    py38-dj42
    py39-dj42
    py310-dj{42,50,51,52}
    py311-dj{42,50,51,52}
    py312-dj{42,50,51,52,60}
    py313-dj{51,52,60}
    py314-dj{52,60}

[testenv]
package = wheel
extras = dev
deps =
    dj42: Django>=4.2,<4.3
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1

set_env =
    PYTHONDEVMODE = 1
commands =
    python \
      -W error::ResourceWarning \
      -W error::DeprecationWarning \
      -W error::PendingDeprecationWarning \
      -m coverage run \
      -m pytest {posargs:tests}
